"""create_mcp_oauth_tables

Revision ID: f0ba93dfa03b
Revises: 968e37cd1960
Create Date: 2026-07-12 12:56:48.977625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ba93dfa03b'
down_revision: Union[str, Sequence[str], None] = '968e37cd1960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_oauth_clients',
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('grant_types', sa.JSON(), nullable=False),
    sa.Column('response_types', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('token_endpoint_auth_method', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('mcp_oauth_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('user_info', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('mcp_oauth_refresh_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('user_info', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('mcp_oauth_sessions',
    sa.Column('google_state', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('code_challenge', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('google_state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_oauth_sessions')
    op.drop_table('mcp_oauth_refresh_tokens')
    op.drop_table('mcp_oauth_codes')
    op.drop_table('mcp_oauth_clients')
    # ### end Alembic commands ###
